import board

USING_BUTTON = False
if USING_BUTTON:
    BUTTON_PIN = board.D1
else:
    BUTTON_PIN = None
SHORT_PRESS_DURATION = 500
LONG_PRESS_DURATION = 2000
BRIGHTNESS = 0.1
AUDIO_VIS_SMOOTHING = 0.18

AUDIO_SERVER_IP = "192.168.0.108"
AUDIO_SERVER_PORT = 8002
AUDIO_SERVER_ENDPOINT = f"http://{AUDIO_SERVER_IP}:{AUDIO_SERVER_PORT}"
REQUEST_TIMEOUT = 10


# PIXEL_PIN = board.D0
# TOTAL_PIXELS = 87

PIXEL_PIN = board.D5
TOTAL_PIXELS = 56
