import os

import board

USING_BUTTON = os.getenv("USING_BUTTON") == 1
TONE = os.getenv("TONE", "warm")
# USING_BUTTON = True
if USING_BUTTON:
    BUTTON_PIN = board.D1
    PIXEL_PIN = board.D0
    TOTAL_PIXELS = 87
    # TOTAL_PIXELS = 56
    LED_PIN = None
else:
    BUTTON_PIN = None
    PIXEL_PIN = board.D5
    TOTAL_PIXELS = 56
    LED_PIN = board.LED
SHORT_PRESS_DURATION = 500
LONG_PRESS_DURATION = 2000
BRIGHTNESS = 0.2
AUDIO_VIS_SMOOTHING = 0.3

AUDIO_SERVER_IP = "192.168.0.100"
AUDIO_SERVER_PORT = 8002

AUDIO_SERVER_ENDPOINT = f"{AUDIO_SERVER_IP}:{AUDIO_SERVER_PORT}"
AUDIO_SERVER_ENDPOINT_HTTP = f"http://{AUDIO_SERVER_ENDPOINT}"
AUDIO_SERVER_ENDPOINT_WS = f"ws://{AUDIO_SERVER_ENDPOINT}"
REQUEST_TIMEOUT = 10

MQTT_HOST = AUDIO_SERVER_IP
MQTT_TOPIC = "audio-values"
MQTT_BROKER_PORT = 1885

UDP_HOST = AUDIO_SERVER_IP
UDP_PORT = 1234


LED_BLINK_DELAY = 0.1

# PIXEL_PIN = board.D0
# TOTAL_PIXELS = 87
